FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    inetutils-ping \
    daemontools \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/data && \
    chmod 777 /app/data  # Ensure writeable

ENV PYTHONPATH=/app
ENV DATABASE_URL=sqlite+aiosqlite:///./data/pinger.db

USER root

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]